import { useEffect, useState } from "react";
import { ApiError } from "../../api/apiClient";
import { getAdminBrandSettings, updateAdminBrandSettings, uploadBrandImage } from "../../api/brandSettingsApi";
import type { AdminBrandSettings, UpdateBrandSettingsRequest } from "../types";
import { useSiteSettings } from "../siteSettings/SiteSettingsContext";

type Props={onUnauthorized:()=>void};
const input="w-full px-3 py-2.5 text-[12px] border border-border bg-background focus:outline-none focus:border-accent";
const empty:UpdateBrandSettingsRequest={brandDisplayName:"",logoFileId:null,logoAltText:"",faviconFileId:null,headerCtaLabel:"",headerCtaUrl:"",defaultMetaTitle:"",defaultMetaDescription:"",defaultOgTitle:null,defaultOgDescription:null,defaultOgImageFileId:null,showServicesLink:true,servicesLabel:"Services",showPortfolioLink:true,portfolioLabel:"Portfolio",showOrderLink:true,orderLabel:"Order",showAboutLink:true,aboutLabel:"About",showContactLink:true,contactLabel:"Contact"};
const requestFrom=(s:AdminBrandSettings):UpdateBrandSettingsRequest=>({...empty,brandDisplayName:s.brandDisplayName,logoFileId:s.logoFileId,logoAltText:s.logoAltText,faviconFileId:s.faviconFileId,headerCtaLabel:s.headerCtaLabel,headerCtaUrl:s.headerCtaUrl,defaultMetaTitle:s.defaultMetaTitle,defaultMetaDescription:s.defaultMetaDescription,defaultOgTitle:s.defaultOgTitle,defaultOgDescription:s.defaultOgDescription,defaultOgImageFileId:s.defaultOgImageFileId,...s.navigation});

export function AdminBrandSettingsPanel({onUnauthorized}:Props){
  const {refresh}=useSiteSettings();
  const [form,setForm]=useState(empty);const [current,setCurrent]=useState<AdminBrandSettings|null>(null);const [busy,setBusy]=useState(true);const [uploading,setUploading]=useState<string|null>(null);const [message,setMessage]=useState("");const [error,setError]=useState("");const [previews,setPreviews]=useState<Record<string,string>>({});
  useEffect(()=>{getAdminBrandSettings().then(x=>{setCurrent(x);setForm(requestFrom(x));}).catch(handle).finally(()=>setBusy(false));},[]);
  function handle(value:unknown){if(value instanceof ApiError&&(value.status===401||value.status===403)){onUnauthorized();return;}setError(value instanceof ApiError?(Object.values(value.errors??{}).flat()[0]??value.message):"The request could not be completed.");}
  function set<K extends keyof UpdateBrandSettingsRequest>(key:K,value:UpdateBrandSettingsRequest[K]){setForm(old=>({...old,[key]:value}));}
  async function upload(key:"logoFileId"|"faviconFileId"|"defaultOgImageFileId",file?:File){if(!file)return;setError("");setUploading(key);try{const x=await uploadBrandImage(file);set(key,x.id);setPreviews(old=>({...old,[key]:URL.createObjectURL(file)}));}catch(e){handle(e);}finally{setUploading(null);}}
  async function save(){setError("");setMessage("");setBusy(true);try{const x=await updateAdminBrandSettings(form);setCurrent(x);setForm(requestFrom(x));await refresh();setMessage("Brand and SEO settings saved.");}catch(e){handle(e);}finally{setBusy(false);}}
  if(busy&&!current)return <p className="text-[12px] text-muted-foreground">Loading brand settings...</p>;
  const uploadBox=(label:string,key:"logoFileId"|"faviconFileId"|"defaultOgImageFileId",url:string|null)=><div><label className="text-[11px] text-muted-foreground">{label}</label><div className="mt-2 flex items-center gap-4">{previews[key]||url?<img src={previews[key]||url||""} alt="Preview" className="h-16 w-28 object-contain border border-border bg-white p-2"/>:<div className="h-16 w-28 border border-dashed border-border flex items-center justify-center text-[10px] text-muted-foreground">No image</div>}<label className="px-3 py-2 border border-border bg-background text-[11px] cursor-pointer hover:border-foreground">{uploading===key?"Uploading...":"Choose image"}<input type="file" accept="image/jpeg,image/png,image/webp" className="hidden" disabled={uploading!==null} onChange={e=>void upload(key,e.target.files?.[0])}/></label>{form[key]&&<button type="button" className="text-[10px] text-destructive" onClick={()=>set(key,null)}>Remove</button>}</div></div>;
  return <div className="space-y-6">
    {error&&<div role="alert" className="border border-destructive/30 bg-card p-3 text-[11px] text-destructive">{error}</div>}{message&&<div className="border border-emerald-300 bg-card p-3 text-[11px] text-emerald-700">{message}</div>}
    <section className="bg-card border border-border p-6 space-y-5"><h2 className="font-serif text-xl">Brand assets</h2><div className="grid md:grid-cols-3 gap-6">{uploadBox("Header / footer logo","logoFileId",current?.logoUrl??null)}{uploadBox("Favicon","faviconFileId",current?.faviconUrl??null)}{uploadBox("Default Open Graph image","defaultOgImageFileId",current?.defaultOgImageUrl??null)}</div><div className="grid md:grid-cols-2 gap-4"><Field label="Brand display name" value={form.brandDisplayName} onChange={v=>set("brandDisplayName",v)}/><Field label="Logo alt text" value={form.logoAltText} onChange={v=>set("logoAltText",v)}/><Field label="Header CTA label" value={form.headerCtaLabel} onChange={v=>set("headerCtaLabel",v)}/><Field label="Header CTA URL" value={form.headerCtaUrl} onChange={v=>set("headerCtaUrl",v)}/></div></section>
    <section className="bg-card border border-border p-6 space-y-4"><h2 className="font-serif text-xl">Default SEO</h2><Field label="Meta title" value={form.defaultMetaTitle} onChange={v=>set("defaultMetaTitle",v)}/><Area label="Meta description" value={form.defaultMetaDescription} onChange={v=>set("defaultMetaDescription",v)}/><div className="grid md:grid-cols-2 gap-4"><Field label="Open Graph title (optional)" value={form.defaultOgTitle??""} onChange={v=>set("defaultOgTitle",v||null)}/><Area label="Open Graph description (optional)" value={form.defaultOgDescription??""} onChange={v=>set("defaultOgDescription",v||null)}/></div></section>
    <section className="bg-card border border-border p-6"><h2 className="font-serif text-xl mb-4">Navigation</h2><div className="grid md:grid-cols-2 gap-4">{(["Services","Portfolio","Order","About","Contact"] as const).map(name=>{const lower=name.toLowerCase() as "services"|"portfolio"|"order"|"about"|"contact";const show=`show${name}Link` as keyof UpdateBrandSettingsRequest;const label=`${lower}Label` as keyof UpdateBrandSettingsRequest;return <div key={name} className="flex items-end gap-3"><label className="flex items-center gap-2 pb-2.5 text-[11px]"><input type="checkbox" checked={form[show] as boolean} onChange={e=>setForm(old=>({...old,[show]:e.target.checked}))}/> Show</label><div className="flex-1"><Field label={`${name} label`} value={form[label] as string} onChange={v=>setForm(old=>({...old,[label]:v}))}/></div></div>})}</div></section>
    <button type="button" onClick={()=>void save()} disabled={busy||uploading!==null} className="bg-foreground text-primary-foreground px-6 py-3 text-[11px] tracking-wide disabled:opacity-50">{busy?"Saving...":"Save Brand / SEO"}</button>
  </div>;
}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="block text-[11px] text-muted-foreground">{label}<input className={`${input} mt-1.5`} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Area({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="block text-[11px] text-muted-foreground">{label}<textarea className={`${input} mt-1.5 min-h-24`} value={value} onChange={e=>onChange(e.target.value)}/></label>}
